from workboard_cli.queries import _is_overdue


def build_summary(items):
    by_category = {"open": 0, "closed": 0, "blocked": 0, "unknown": 0}
    overdue_count = 0
    blocked_count = 0
    by_owner = {}

    for item in items:
        cat = item.get("stageCategory", "unknown")
        by_category[cat] = by_category.get(cat, 0) + 1

        if _is_overdue(item):
            overdue_count += 1
        if cat == "blocked":
            blocked_count += 1

        owner = item.get("deliveryOwner")
        if owner:
            name = owner.get("displayName") or "Unknown"
            if name not in by_owner:
                by_owner[name] = {"open": 0, "overdue": 0}
            by_owner[name]["open"] = by_owner[name].get("open", 0) + 1
            if _is_overdue(item):
                by_owner[name]["overdue"] = by_owner[name].get("overdue", 0) + 1

    return {
        "count": len(items),
        "totalItems": len(items),
        "byStageCategory": by_category,
        "overdueCount": overdue_count,
        "blockedCount": blocked_count,
        "byOwner": by_owner,
    }


def render_markdown_summary(summary, site_url, retrieved_at):
    lines = [
        "# WorkBoard Manager Summary",
        "",
        f"**Retrieved:** {retrieved_at}",
        f"**Source:** {site_url}",
        "",
        "## Overview",
        "",
        "| Metric | Count |",
        "|---|---|",
        f"| Total items | {summary['totalItems']} |",
        f"| Overdue | {summary['overdueCount']} |",
        f"| Blocked | {summary['blockedCount']} |",
        "",
        "## By Stage",
        "",
    ]
    for cat, count in summary["byStageCategory"].items():
        lines.append(f"- **{cat.capitalize()}**: {count}")

    lines.extend(["", "## By Owner", ""])
    for name, data in sorted(summary["byOwner"].items()):
        lines.append(f"- **{name}**: {data['open']} open, {data['overdue']} overdue")

    lines.extend(["", "---", "*Report generated by workboard-cli*"])
    return "\n".join(lines)
